[package]

name = "paxy-cli"
version.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
exclude.workspace = true
categories = ["command-line-utilities"]
documentation.workspace = true
readme.workspace = true
edition.workspace = true


[dependencies]

paxy = { workspace = true }

# Logging
tracing = { workspace = true }
log = { workspace = true, features = ["serde"] }

# Error handling
snafu = {workspace = true}

# Internationalization
fluent = { workspace = true }

# CLI
clap = { workspace = true, features = ["cargo", "env"] }
clap-verbosity-flag = { workspace = true }
anstream = { workspace = true }
owo-colors = { workspace = true }
console = { workspace = true }
